env: order-dev3.yml
spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql:///pm111
    driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
      host: 192.168.3.7
      username: guest
      password: guest
      port: 5672
  application:
    name: order
server:
  port: 8082
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
