env: order-dev6.yml

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql:///xmjy?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order
  rabbitmq:
    host: 192.168.199.160
    username: guest
    password: guest
    port: 5672
server:
  port: 8082
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
