env: product-dev7.yml

spring:
  application:
    name: product
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql:///xmjy
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.159
    username: guest
    password: guest
    port: 5672
server:
  port: 8081
